version: '3.8'

services:
  app1: &api
    image: hyperf-skeleton:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    ports:
      - "9501:9501"
    networks:
      - backend
      - payment-processor
    volumes:
      - ./:/opt/www
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"

  app2:
    <<: *api
    ports:
      - "9502:9501"
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

# Redis removido - não será usado

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - backend
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

# Redis removido - não será usado
